#!/usr/bin/env python3
"""Fabrik sound-effects generator — create game audio with the ElevenLabs SFX API.

Examples
--------
  # generate EVERY sound effect
  python generate_sfx.py --all

  # (re)generate just one sound
  python generate_sfx.py --sfx milestone

  # regenerate a few
  python generate_sfx.py --sfx click place car_ready

  # regenerate a whole category (ui | world | factory | car | event)
  python generate_sfx.py --category ui

  # list everything that can be generated
  python generate_sfx.py --list

  # run with no args for an interactive menu
  python generate_sfx.py

Options
-------
  --api-key KEY     overrides ELEVENLABS_API_KEY env var
  --out DIR         output folder (default: ./generated/sfx)
  --model ID        model id (default eleven_text_to_sound_v2, supports looping)
  --format FMT      output_format (default mp3_44100_128)
  --force           regenerate even if the file already exists
  --duration SEC    override the duration for the selected sounds
  --influence N     override prompt_influence (0..1) for the selected sounds

After generating, the script (re)writes generated/sfx_manifest.js, which the
game loads automatically. Missing sounds are simply silent in-game.
"""

from __future__ import annotations
import argparse
import json
import os
import sys
import time

import sfx_specs as A

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "generated", "sfx")
MANIFEST = os.path.join(HERE, "generated", "sfx_manifest.js")


def out_path(out_dir: str, spec: A.SfxSpec) -> str:
    return os.path.join(out_dir, spec.game_id + ".mp3")


def resolve_selection(args) -> list:
    chosen = []
    if args.all:
        chosen = list(A.SPECS)
    else:
        if args.category:
            for cat in args.category:
                if cat not in A.CATEGORIES:
                    sys.exit(f"Unknown category '{cat}'. Choices: {', '.join(A.CATEGORIES)}")
                chosen += A.specs_for_category(cat)
        if args.sfx:
            for sid in args.sfx:
                if sid not in A.BY_ID:
                    sys.exit(f"Unknown sound id '{sid}'. Use --list to see all ids.")
                chosen.append(A.BY_ID[sid])
    seen, ordered = set(), []
    for s in chosen:
        if s.id not in seen:
            seen.add(s.id)
            ordered.append(s)
    return ordered


def print_list():
    print("Fabrik sound effects (%d total):\n" % len(A.SPECS))
    for cat in A.CATEGORIES:
        items = A.specs_for_category(cat)
        print(f"  [{cat}]  ({len(items)})")
        for s in items:
            tag = "loop " if s.loop else "     "
            print(f"      {s.id:<12} {tag}{s.duration:>4.1f}s")
        print()
    print("Generate with:  --all  |  --category <cat>  |  --sfx <id> [<id> ...]")


def interactive() -> list:
    print_list()
    print("\nWhat do you want to generate?")
    print("  [a] all   [c] a category   [i] specific id(s)   [q] quit")
    choice = input("> ").strip().lower()
    if choice == "a":
        return list(A.SPECS)
    if choice == "c":
        return A.specs_for_category(input(f"category ({', '.join(A.CATEGORIES)}): ").strip())
    if choice == "i":
        return [A.BY_ID[i] for i in input("ids (space separated): ").split() if i in A.BY_ID]
    return []


def write_manifest(out_dir: str):
    sounds = {}
    for s in A.SPECS:
        if os.path.exists(out_path(out_dir, s)):
            sounds[s.game_id] = {"file": s.game_id + ".mp3", "loop": s.loop, "volume": s.volume}
            if s.loop_end is not None:
                sounds[s.game_id]["loopEnd"] = s.loop_end
    manifest = {"base": "assets/generated/sfx/", "sounds": sounds}
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    js = "// Auto-generated by assets/generate_sfx.py — do not edit by hand.\n"
    js += "window.FAB_SFX = " + json.dumps(manifest, indent=2) + ";\n"
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"\nWrote sfx_manifest.js with {len(sounds)} sound(s).")


def main():
    ap = argparse.ArgumentParser(description="Generate Fabrik sound effects with ElevenLabs.")
    ap.add_argument("--all", action="store_true", help="generate every sound")
    ap.add_argument("--category", nargs="+", help="generate whole categories")
    ap.add_argument("--sfx", nargs="+", help="generate specific sound ids")
    ap.add_argument("--list", action="store_true", help="list all sounds and exit")
    ap.add_argument("--api-key", dest="api_key", default=None)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--model", default="eleven_text_to_sound_v2")
    ap.add_argument("--format", dest="fmt", default="mp3_44100_128")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--duration", type=float, default=None, help="override duration (s)")
    ap.add_argument("--influence", type=float, default=None, help="override prompt_influence")
    args = ap.parse_args()

    if args.list:
        print_list()
        return

    os.makedirs(args.out, exist_ok=True)

    specs = resolve_selection(args)
    if not specs and not (args.all or args.category or args.sfx):
        specs = interactive()
    if not specs:
        print("Nothing selected. Try --all, --category <cat>, --sfx <id>, or --list.")
        return

    todo = [s for s in specs if args.force or not os.path.exists(out_path(args.out, s))]
    skipped = len(specs) - len(todo)
    if skipped:
        print(f"({skipped} already exist — use --force to redo them)")
    if not todo:
        write_manifest(args.out)
        return

    total_secs = sum((args.duration or s.duration) for s in todo)
    print(f"Generating {len(todo)} sound(s) with model '{args.model}' "
          f"(~{total_secs:.0f}s of audio; uses ElevenLabs credits).\n")

    from elevenlabs_client import ElevenLabsSfxClient
    client = ElevenLabsSfxClient(api_key=args.api_key, model_id=args.model, output_format=args.fmt)

    ok, fail = 0, 0
    for i, spec in enumerate(todo, 1):
        dur = args.duration if args.duration is not None else spec.duration
        infl = args.influence if args.influence is not None else spec.influence
        print(f"[{i}/{len(todo)}] {spec.id} ({spec.category}, {dur:.1f}s{', loop' if spec.loop else ''}) ...")
        try:
            audio = client.generate(spec.prompt, duration_seconds=dur, prompt_influence=infl, loop=spec.loop)
            with open(out_path(args.out, spec), "wb") as f:
                f.write(audio)
            print(f"      saved {spec.game_id}.mp3  ({len(audio) // 1024} KB)")
            ok += 1
        except Exception as exc:
            print(f"      FAILED: {exc}")
            fail += 1
        time.sleep(0.3)

    print(f"\nDone. {ok} ok, {fail} failed.")
    write_manifest(args.out)
    print("Reload index.html to hear the new sounds.")


if __name__ == "__main__":
    main()
