#!/usr/bin/env python3
"""Fabrik asset generator — create game art with Google's Gemini image models.

Examples
--------
  # generate EVERYTHING
  python generate_assets.py --all

  # (re)generate just the player sprite sheet
  python generate_assets.py --asset player

  # regenerate a few specific assets
  python generate_assets.py --asset machine_drill machine_furnace car_super

  # regenerate a whole category (player | machines | items | cars | tiles)
  python generate_assets.py --category machines

  # list everything that can be generated
  python generate_assets.py --list

  # run with no args for an interactive menu
  python generate_assets.py

Options
-------
  --model MODEL     gemini-2.5-flash-image (default) | gemini-3.1-flash-image | gemini-3-pro-image
  --api-key KEY     overrides GEMINI_API_KEY / GOOGLE_API_KEY env var
  --out DIR         output folder (default: ./generated)
  --force           regenerate even if the PNG already exists
  --no-postprocess  save the raw model output (skip background removal / resize)
  --keep-raw        also save the unprocessed image next to the final one

After generating, the script (re)writes generated/manifest.js, which the game
loads automatically. Anything not yet generated falls back to built-in
placeholder art, so the game is always playable.
"""

from __future__ import annotations
import argparse
import json
import os
import sys
import time

import asset_specs as A

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "generated")
PRICE_PER_IMAGE = 0.067  # approx USD/image for gemini-3.1-flash-image at 1K
                         # ($60 / 1M image-output tokens; a 1024px image ≈ 1120 tokens)


# --------------------------------------------------------------------------- helpers
def out_path(out_dir: str, spec: A.AssetSpec) -> str:
    return os.path.join(out_dir, spec.game_id + ".png")


def resolve_selection(args) -> list:
    """Return the ordered list of AssetSpec to generate based on CLI flags."""
    chosen = []
    if args.all:
        chosen = list(A.SPECS)
    else:
        if args.category:
            for cat in args.category:
                if cat not in A.CATEGORIES:
                    sys.exit(f"Unknown category '{cat}'. Choices: {', '.join(A.CATEGORIES)}")
                chosen += A.specs_for_category(cat)
        if args.asset:
            for aid in args.asset:
                if aid not in A.BY_ID:
                    sys.exit(f"Unknown asset id '{aid}'. Use --list to see all ids.")
                chosen.append(A.BY_ID[aid])
    # de-dup, preserve order
    seen, ordered = set(), []
    for s in chosen:
        if s.id not in seen:
            seen.add(s.id)
            ordered.append(s)
    return ordered


def print_list():
    print("Fabrik assets (%d total):\n" % len(A.SPECS))
    for cat in A.CATEGORIES:
        items = A.specs_for_category(cat)
        print(f"  [{cat}]  ({len(items)})")
        for s in items:
            kind = f"sheet {s.rows}x{s.cols}" if s.is_sheet else "single"
            print(f"      {s.id:<22} {kind}")
        print()
    print("Generate with:  --all  |  --category <cat>  |  --asset <id> [<id> ...]")


def interactive(args) -> list:
    print_list()
    print("\nWhat do you want to generate?")
    print("  [a] all   [c] a category   [i] specific id(s)   [q] quit")
    choice = input("> ").strip().lower()
    if choice == "a":
        return list(A.SPECS)
    if choice == "c":
        cat = input(f"category ({', '.join(A.CATEGORIES)}): ").strip()
        return A.specs_for_category(cat)
    if choice == "i":
        ids = input("ids (space separated): ").split()
        return [A.BY_ID[i] for i in ids if i in A.BY_ID]
    return []


def write_manifest(out_dir: str):
    """Write generated/manifest.js listing every asset that has a PNG on disk."""
    images = {}
    for s in A.SPECS:
        if os.path.exists(out_path(out_dir, s)):
            entry = {"file": s.game_id + ".png"}
            if s.is_sheet:
                entry["cols"] = s.cols
                entry["rows"] = s.rows
            images[s.game_id] = entry
    manifest = {"base": "assets/generated/", "images": images}
    js = "// Auto-generated by assets/generate_assets.py — do not edit by hand.\n"
    js += "window.FAB_ASSETS = " + json.dumps(manifest, indent=2) + ";\n"
    with open(os.path.join(out_dir, "manifest.js"), "w", encoding="utf-8") as f:
        f.write(js)
    print(f"\nWrote manifest.js with {len(images)} image(s).")


# --------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description="Generate Fabrik game art with Gemini.")
    ap.add_argument("--all", action="store_true", help="generate every asset")
    ap.add_argument("--category", nargs="+", help="generate whole categories")
    ap.add_argument("--asset", nargs="+", help="generate specific asset ids")
    ap.add_argument("--list", action="store_true", help="list all assets and exit")
    ap.add_argument("--model", default="gemini-3.1-flash-image", help="image model id")
    ap.add_argument("--api-key", dest="api_key", default=None)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--force", action="store_true", help="overwrite existing PNGs")
    ap.add_argument("--no-postprocess", dest="postprocess", action="store_false")
    ap.add_argument("--keep-raw", action="store_true", help="also save raw model output")
    args = ap.parse_args()

    if args.list:
        print_list()
        return

    os.makedirs(args.out, exist_ok=True)

    specs = resolve_selection(args)
    if not specs and not (args.all or args.category or args.asset):
        specs = interactive(args)
    if not specs:
        print("Nothing selected. Try --all, --category <cat>, --asset <id>, or --list.")
        return

    # skip ones that already exist unless --force
    todo = [s for s in specs if args.force or not os.path.exists(out_path(args.out, s))]
    skipped = len(specs) - len(todo)
    if skipped:
        print(f"({skipped} already exist — use --force to redo them)")
    if not todo:
        write_manifest(args.out)
        return

    est = len(todo) * PRICE_PER_IMAGE
    print(f"Generating {len(todo)} asset(s) with model '{args.model}' "
          f"(rough cost ~${est:.2f}).\n")

    # lazy imports so --list works without the SDK installed
    from gemini_client import GeminiImageClient
    import postprocess
    from PIL import Image

    client = GeminiImageClient(api_key=args.api_key, model=args.model)

    ok, fail = 0, 0
    for i, spec in enumerate(todo, 1):
        print(f"[{i}/{len(todo)}] {spec.id} ({spec.category}) ...")
        try:
            refs = []
            if spec.ref and spec.ref in A.BY_ID:
                rp = out_path(args.out, A.BY_ID[spec.ref])
                if os.path.exists(rp):
                    refs.append(Image.open(rp))
            img = client.generate(spec.prompt, references=refs, aspect_ratio=spec.aspect)
            if args.keep_raw:
                img.save(out_path(args.out, spec).replace(".png", ".raw.png"))
            if args.postprocess:
                img = postprocess.process(img, spec)
            img.save(out_path(args.out, spec))
            print(f"      saved {spec.game_id}.png  ({img.size[0]}x{img.size[1]})")
            ok += 1
        except Exception as exc:
            print(f"      FAILED: {exc}")
            fail += 1
        time.sleep(0.3)  # be gentle with rate limits

    print(f"\nDone. {ok} ok, {fail} failed.")
    write_manifest(args.out)
    print("Reload index.html to see the new art.")


if __name__ == "__main__":
    main()
